# Generated by Django 3.2.5 on 2021-07-10 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='DummyCategory', max_length=254, verbose_name='Name')),
                ('description', models.TextField(max_length=5000, null=True, verbose_name='Description')),
                ('image', models.ImageField(upload_to='categories/', verbose_name='Image')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Name')),
                ('rating', models.IntegerField(choices=[(1, 'Bad'), (2, 'Nah'), (3, 'Norm'), (4, 'Good'), (5, 'Awesome')], default=0, verbose_name='Rating')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('review', models.TextField(max_length=5000)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='DummyItem', max_length=254, verbose_name='Item_name')),
                ('rating', models.IntegerField(choices=[(1, 'Bad'), (2, 'Nah'), (3, 'Norm'), (4, 'Good'), (5, 'Awesome')], null=True, verbose_name='Rating')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantity')),
                ('discount', models.BooleanField(default=False, verbose_name='Discount')),
                ('color', models.CharField(choices=[('wh', 'White'), ('blm', 'Black'), ('bl', 'Blue')], max_length=5, verbose_name='Colors')),
                ('slug', models.SlugField(default='dummy-item', verbose_name='Slug')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
            ],
            options={
                'verbose_name_plural': "Item's",
                'ordering': ['-price'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('default', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.item')),
            ],
        ),
    ]
