# Generated by Django 3.2.5 on 2021-07-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210711_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.AddField(
            model_name='category',
            name='category_url',
            field=models.CharField(max_length=255, null=True, verbose_name='Category_Url'),
        ),
    ]
