# Generated by Django 3.2.5 on 2021-07-16 08:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0008_auto_20210716_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='items',
            new_name='item',
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'item')},
        ),
    ]
